### ISSUE TITLE
QtFirebaseExample not showing ads

### ISSUE THREAD

**Issue by paoletto** [Larpon/QtFirebaseExample#22]
Qt  5.12.3 
Device: F5122 w. Android 7.1.1
QtFirebase: latest
QtFirebaseExample: latest
firebase: 6.1.0
I followed the instructions, and succesfully built and deployed the app to an android device using a Qt 5.12.3.
However, the app only shows test ads, and the console permanently reports No Fill error (see attachments), even after tapping the reload buttons.

It would be good to at least know if the author can reproduce this problem locally.

![photo_2019-09-28_18-32-43](https://user-images.githubusercontent.com/6912425/65819562-76b54c00-e21e-11e9-8342-c2bdb935df44.jpg)
![photo_2019-09-28_18-32-50](https://user-images.githubusercontent.com/6912425/65819563-774de280-e21e-11e9-959c-0f9109ba0a2b.jpg)

**Comment by larpon** [comment]
Hey @paoletto! Welcome to the project! 🙂 That's very much expected behaviour in the example app. This is all part of the way Google protect the ad-system against fraud. If you have added your device id to the test devices list this is pretty much what you get.

However everything should work as expected if you do a release build via Google Play. I haven't been able to get video test ads on any of my development devices while in test mode - for unknown reasons.

**Comment by paoletto** [comment]
@Larpon thanks for clarifying this aspect! i wish it was documented :-)
I'm new to firebase and admob and I did not know the way it works in detail..

**Comment by larpon** [comment]
@paoletto no problem :)

> i wish it was documented

Yeah I understand your frustration. Unfortunately we can't keep up with documenting all the quirks of Firebase and AdMob as we support this in our spare time. Part of the problem is that both are (mostly) closed platforms hidden at some Google servers somewhere. So we only have Google's official channels and StackOverflow to figure out things if no one in our small user base has any suggestions. This specific issue you're having seem to be only present on some devices, configurations and Firebase SDK versions. (And in my personal setup as well!)

Anyway - I hope everything works out for you and your project!

**Comment by larpon** [comment]
Tried to throw in some guards against this in the README :)
