### ISSUE TITLE
Make No rule to make target

### ISSUE THREAD

**Issue by Trikos** [Larpon/QtFirebaseExample#24]
Hi, Im trying to compile for Android and I get this error:
make: *** No rule to make target 'C:\QT\Firebase\QtFirebaseExample\extensions\QtFirebase\firebase_cpp_sdk\libs\android\arm64-v8a\c++\libfirebase_app.a', needed by 'libApp.so'.  Stop.

I followed all the steps but everything lead here at this error.
If I try to compile it for windows it works.
Thank you

**Comment by larpon** [comment]
Hi @Trikos - are you by chance using the recently introduced [Android multi arch build in one go](https://www.kdab.com/qt-for-android-better-than-ever-before/) feature?

**Comment by Trikos** [comment]
Well, Im not sure, but Im using Qt 5.13 right now and I solved the problem just using the direct link for SDK instead of symbolink link because it doesnt work. Then I recompile everything and it works.

**Comment by Trikos** [comment]
Now my problem is gather all the stuff and bring them to my project. There are too much files to copy that Im gonna be lost doing it. Do you have some suggestion?
Also I was wondering, using the Messaging I was able to received from the server but I can only see them into the console you created in the program and they dont appear in the drop down menu where all notifications shoullld be

**Comment by larpon** [comment]
If Windows are your host platform, symlinks probably won't work. The symlink trick is for Linux and Mac - I'll hint that in the docs, thanks!

 I agree that the project isn't ideal to setup. The problem is the many technologies and different build systems used. Qmake is not an ideal solution to automate things. So here we are 🙂 The best way would probably be for you to start a fresh pull to your own project and then follow the docs from there. You need to be careful not mixing old app IDs etc. that's a common pitfall. If something doesn't work then look at your reference implementation (in this case QtFirebaseExample) and see how it's  setup.


Messaging works on my setup - but for you to get notifications you'll need to close the app and then send the message from your Firebase console or Firebase integration. Right now I can't give the public access to QtFirebase's console so you'll have to try with your own IDs 🙂

If the app is open Firebase leaves it up to you to handle the message, if not, it uses a notification.

Hope you get it running!

**Comment by Trikos** [comment]
Thanks for the clear response. One more little question: so you are saying that if my app is closed I should receive the notification through the Android system, instead if my app is open I should handle by myself? Right? Because right now when the app is close it doesnt send me the notification

**Comment by larpon** [comment]
> so you are saying that if my app is closed I should receive the notification through the Android system, instead if my app is open I should handle by myself?

Yes, I've just sent this out to all QtFirebaseExample apps (both iOS and Android):
![image](https://user-images.githubusercontent.com/768942/77251851-04637880-6c51-11ea-976e-c930525b9f40.png)

(^The actual notification from my phone)

**Comment by Trikos** [comment]
I have changed my google-services.json so I didnt received it. I reversed to your google-services.json do you mind to send a notification again to all devices?
Thank you
PS Can I contact you using some more direct channel? Discord or similar?
TOP

**Comment by larpon** [comment]
@Trikos - I haven't got time to give personal support - I sent out a few messages yesterday. In the end you'll have to setup your own firebase apps and ids in the console :)
